name: Update Case Data 

on:
  schedule:
    - cron: "35 1 * * *"
  workflow_dispatch:
  push:
    paths:
      - python/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        pip install -r python-requirements.txt
    - name: Run python script to update info
      run: |
        cd scripts
        bash update.sh
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Commit Changes
      run: |
        git add .
        git commit -m "Update Data using Python Script"
        git push origin
