name: Update Case Data 

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        pip install -r python-requirements.txt
    - name: Run python script to update info
      run: |
        cd python
        python graphs.py
        python noverview.py
        python overview.py
        python ntable.py
        python tables.py
        python pcd.py
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Commit Changes
      run: |
        git add .
        git commit -m "Update Data using Python Script"
        git push origin
